// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALvnWBmGfaBZPVVXMRboIM2r4AYXp1T8A',
    appId: '1:1040332827732:web:bc91b43cb2e730c34bd1c1',
    messagingSenderId: '1040332827732',
    projectId: 'uzbek-messag',
    authDomain: 'uzbek-messag.firebaseapp.com',
    databaseURL: 'https://uzbek-messag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uzbek-messag.appspot.com',
    measurementId: 'G-C0NE2E2RZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzL0F-usDdJTR_GYhhUWXK4ThXQOx_IM',
    appId: '1:1040332827732:android:4c3709f47504850b4bd1c1',
    messagingSenderId: '1040332827732',
    projectId: 'uzbek-messag',
    databaseURL: 'https://uzbek-messag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uzbek-messag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVh8pMYjyb-FHw4K3vv-uPhYrSu8BGihw',
    appId: '1:1040332827732:ios:8d1b0d3dd738b01a4bd1c1',
    messagingSenderId: '1040332827732',
    projectId: 'uzbek-messag',
    databaseURL: 'https://uzbek-messag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uzbek-messag.appspot.com',
    iosBundleId: 'dev.nematov.fireChat',
  );
}
